version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic
    - revive

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0