version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic

linter-config:
  govet:
    shadow: true
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp

issues:
  exclude-dirs-use-default: false
  max-same-issues: 0
  max-per-linter: 0